"""
DO NOT EDIT THIS FILE!!!
"""
import os
import shutil
import unittest

import boto3
import dotenv
import tensorflow as tf

from seminar6 import PATH_TO_DATA, YOUR_GIT_USER

PATH_TO_LOCAL_MODEL = 'models/model_6'
PATH_TO_S3_MODEL = 'models/model_6_s3'


class TestAccuracyDemo(unittest.TestCase):
    def testCategoricalAccuracy(self):
        m = tf.keras.metrics.CategoricalAccuracy()
        y_true = tf.convert_to_tensor([[0, 0, 1], [0, 1, 0]])
        y_pred = tf.convert_to_tensor([[0.1, 0.9, 0.8], [0.05, 0.95, 0]])
        m.update_state(y_true, y_pred)
        res = m.result().numpy()
        self.assertEqual(res, 0.5)


class TestModelLocal(unittest.TestCase):
    def test_model(self):
        model = tf.keras.models.load_model(PATH_TO_LOCAL_MODEL)
        X = tf.ones((1, 180, 180, 3))
        y = model(X)
        self.assertIsInstance(y, tf.Tensor)


class TestModelS3(unittest.TestCase):
    def test_model_s3(self):
        config = dotenv.dotenv_values('.env')
        ACCESS_KEY = config['ACCESS_KEY']
        SECRET_KEY = config['SECRET_KEY']

        client = boto3.client(
            's3',
            endpoint_url='https://storage.yandexcloud.net',
            aws_access_key_id=ACCESS_KEY,
            aws_secret_access_key=SECRET_KEY
        )

        client.download_file('neuralnets2023',
<<<<<<< HEAD
                             os.path.join(YOUR_GIT_USER, 'model_6.zip'),
=======
                             f'{YOUR_GIT_USER}/model_6.zip',
>>>>>>> labintsev/master
                             PATH_TO_S3_MODEL+'.zip')
        shutil.unpack_archive(PATH_TO_S3_MODEL+'.zip', PATH_TO_S3_MODEL)
        model = tf.keras.models.load_model(PATH_TO_S3_MODEL)
        test_ds = tf.keras.utils.image_dataset_from_directory(
            os.path.join(PATH_TO_DATA, "PetImages"),
            validation_split=0.2,
            subset="validation",
            seed=1337,
            image_size=(180, 180),
            batch_size=32,
        )
        score = model.evaluate(test_ds)
        self.assertGreater(score[1], 0.8)


if __name__ == '__main__':
    unittest.main()
