"""
DO NOT EDIT THIS FILE!!!
"""
import os
import shutil
import unittest

import boto3
import dotenv

from seminar7 import YOUR_GIT_USER, validate

PATH_TO_S3_MODEL = 'models/model_7_s3'


class TestModelS3(unittest.TestCase):
    def test_model_s3(self):
        config = dotenv.dotenv_values('.env')
        ACCESS_KEY = config['ACCESS_KEY']
        SECRET_KEY = config['SECRET_KEY']

        client = boto3.client(
            's3',
            endpoint_url='https://storage.yandexcloud.net',
            aws_access_key_id=ACCESS_KEY,
            aws_secret_access_key=SECRET_KEY
        )

        client.download_file('neuralnets2023',
<<<<<<< HEAD
                             os.path.join(YOUR_GIT_USER, 'model_7.zip'),
                             PATH_TO_S3_MODEL+'.zip')
        shutil.unpack_archive(PATH_TO_S3_MODEL+'.zip', PATH_TO_S3_MODEL)
        accuracy, precision = validate(PATH_TO_S3_MODEL)
        self.assertGreater(accuracy, 0.95)
        self.assertGreater(precision, 0.95)
=======
                             YOUR_GIT_USER + '/model_7.zip',
                             PATH_TO_S3_MODEL+'.zip')
        shutil.unpack_archive(PATH_TO_S3_MODEL+'.zip', PATH_TO_S3_MODEL)
        accuracy, precision, recall = validate(PATH_TO_S3_MODEL)
        self.assertGreater(accuracy, 0.95)
        self.assertGreater(precision, 0.95)
        self.assertGreater(recall, 0.9)
>>>>>>> labintsev/master


if __name__ == '__main__':
    unittest.main()
